export const PERMISSIONS = {
  DASHBOARD: "dashboard:view",
  BOOKINGS_VIEW: "bookings:view",
  BOOKINGS_MANAGE: "bookings:manage",
  ORDERS_VIEW: "orders:view",
  ORDERS_MANAGE: "orders:manage",
  PRODUCTS_VIEW: "products:view",
  PRODUCTS_MANAGE: "products:manage",
  SERVICES_VIEW: "services:view",
  SERVICES_MANAGE: "services:manage",
  STYLISTS_VIEW: "stylists:view",
  STYLISTS_MANAGE: "stylists:manage",
  BLOG_VIEW: "blog:view",
  BLOG_MANAGE: "blog:manage",
  GALLERY_VIEW: "gallery:view",
  GALLERY_MANAGE: "gallery:manage",
  REVIEWS_VIEW: "reviews:view",
  REVIEWS_MANAGE: "reviews:manage",
  COUPONS_VIEW: "coupons:view",
  COUPONS_MANAGE: "coupons:manage",
  GIFTCARDS_VIEW: "giftcards:view",
  GIFTCARDS_MANAGE: "giftcards:manage",
  MESSAGES_VIEW: "messages:view",
  MESSAGES_MANAGE: "messages:manage",
  USERS_VIEW: "users:view",
  USERS_MANAGE: "users:manage",
  OPENINGS_MANAGE: "openings:manage",
  SETTINGS_MANAGE: "settings:manage",
  CUSTOMERS_VIEW: "customers:view",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
